# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/cespare/xxhash"
  version = "1.1.0"

[[constraint]]
  name = "github.com/dchest/siphash"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/minio/blake2b-simd"

[[constraint]]
  branch = "master"
  name = "github.com/minio/highwayhash"

[[constraint]]
  name = "github.com/pierrec/xxHash"
  version = "0.1.1"

[[constraint]]
  name = "github.com/spaolacci/murmur3"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/vova616/xxhash"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
