required = [
  "github.com/twmb/murmur3",
]

[[constraint]]
  name = "github.com/cespare/xxhash"
  version = "1.1.0"

[[constraint]]
  name = "github.com/dchest/siphash"
  version = "1.2.1"

[[constraint]]
  name = "github.com/pierrec/xxHash"
  version = "0.1.1"

[[constraint]]
  name = "github.com/spaolacci/murmur3"
  version = "1.1.0"

[[constraint]]
  name = "github.com/twmb/murmur3"
  branch = "master"

[[constraint]]
  name = "github.com/minio/blake2b-simd"
  branch = "master"

[[constraint]]
  name = "github.com/minio/highwayhash"
  branch = "master"

[[constraint]]
  name = "github.com/vova616/xxhash"
  branch = "master"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
